//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sesi10.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactiondetail
    {
        public int transactionId { get; set; }
        public int clothId { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual cloth cloth { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
