//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternSoftwareDesign_S4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cloth()
        {
            this.transaction_detail = new HashSet<transaction_detail>();
        }
    
        public string id { get; set; }
        public string brand { get; set; }
        public string size { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> price { get; set; }
        public string cloth_type_id { get; set; }
    
        public virtual cloth_types cloth_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_detail> transaction_detail { get; set; }
    }
}
