//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternSoftwareDesign_S4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_detail
    {
        public string Id { get; set; }
        public string cloth_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual cloth cloth { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
