//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternSoftwareDesign_S4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public string Id { get; set; }
        public string userId { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string payment_id { get; set; }
    
        public virtual payment payment { get; set; }
        public virtual transaction_detail transaction_detail { get; set; }
        public virtual user user { get; set; }
    }
}
