//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qualif.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowTransaction()
        {
            this.BorrowDetails = new HashSet<BorrowDetail>();
        }
    
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowDetail> BorrowDetails { get; set; }
        public virtual User User { get; set; }
    }
}
